from pathlib import Path
import os
import subprocess
import sys

ROOT = Path(__file__).resolve().parent
ENV = os.environ.copy()
ENV['PYTHONUTF8'] = '1'
ENV['PYTHONIOENCODING'] = 'utf-8'


def run_verifier(path: Path) -> None:
    print(f'===== {path.name} =====')
    result = subprocess.run([sys.executable, str(path)], cwd=ROOT, env=ENV)
    if result.returncode:
        raise SystemExit(result.returncode)


ordered = [
    'S04', 'S05', 'S06', 'S07', 'S08', 'S09', 'S10', 'S11', 'S12', 'S13',
    'S14A', 'S14B', 'S15A', 'S15B', 'S16A', 'S16B', 'S16C', 'S17A', 'S17B',
    'S18A', 'S18B', 'S18C'
]
for tag in ordered:
    file_path = ROOT / f'VERIFY_{tag}.py'
    if file_path.exists():
        run_verifier(file_path)

for verifier in [
    'VERIFY_S18C_HARDENING_R1.py',
    'VERIFY_S19C_SOURCE.py',
    'VERIFY_R6_LAUNCH_KIT.py',
    'VERIFY_R14_MAIN_LOCATION_OWNERSHIP.py',
    'VERIFY_R7_LOGIC_PHYSICS.py',
    'VERIFY_R8_UE58_TARGETS.py',
    'VERIFY_R9_UHT_TRAUMA.py',
    'VERIFY_R10_CXX_BATCH_FIX.py',
    'VERIFY_R11_VISUAL_FOUNDATION.py',
    'VERIFY_FOLIAGE_RUNTIME_PASS_10.py',
    'VERIFY_PASS45_BLOCK0_GROUND_FOUNDATION.py',
    'VERIFY_PASS45_BLOCK0_REGIONAL_GROUND_DETAIL.py',
    'VERIFY_PASS45_BLOCK0_RUNTIME_HANDOFF.py',
    'VERIFY_PASS45_CONTENT_RUNTIME_WIRING.py',
    'VERIFY_GAMEPLAY_INPUT_PASS_31.py',
    'VERIFY_MUSEUM_LAYER_BUDGET_PASS_32.py',
    'VERIFY_RUNTIME_ACCEPTANCE_PASS_33.py',
    'VERIFY_RUNTIME_LOCATION_MAP_PASS_35.py',
    'VERIFY_WEAPON_MATERIAL_LOWCPU_PERF_PASS_36.py',
    'VERIFY_VISIBLE_MUSEUM_WEAPON_PALETTE_PASS_37.py',
    'VERIFY_RUNTIME_RUNAWAY_HEAT_PASS_38.py',
    'VERIFY_VISUAL_QUALITY_TICK_BUDGET_PASS_39.py',
    'VERIFY_POSTSTART_FRAME_BUDGET_PASS_40.py',
    'VERIFY_INPUT_RECOVERY_POLL_BUDGET_PASS_41.py',
    'VERIFY_PRODUCTION_VEHICLE_GROUND_RACK_PASS_42.py',
    'VERIFY_SLATE_RENDER_TARGET_STARTUP_PASS_43.py',
    'VERIFY_RUNTIME_MAP_SPAWN_FPS_ASSETS_PASS_44.py',
    'VERIFY_RUNTIME_RECOVERY_PASS_45.py',
    'VERIFY_PASS45_LOCAL_BUILD_IMPORT_REGRESSION.py',
    'VERIFY_PASS45_WEAPON_MATERIAL_DEPENDENCY_AUDIT.py',
    'VERIFY_PASS45_FALLBACK_MATERIAL_TEXTURE_GUARD.py',
    'VERIFY_PASS45_WEAPON_MUZZLE_DROP_PHYSICS.py',
    'VERIFY_PASS45_WEAPON_ACTION_MATRIX.py',
    'VERIFY_PASS45_WEAPON_ADS_ALIGNMENT.py',
    'VERIFY_PASS45_WEAPON_AUDIO_FALLBACK.py',
    'VERIFY_PASS45_PRIMITIVE_WEAPON_RETIREMENT.py',
    'VERIFY_PASS45_CHARACTER_PROXY_RETIREMENT.py',
    'VERIFY_PASS45_COMBAT_DISMEMBERMENT_PROXY_RETIREMENT.py',
    'VERIFY_PASS45_GRENADE_SMOKE_PRIMITIVE_RETIREMENT.py',
    'VERIFY_PASS45_GRENADE_TYPE_PRESENTATION_LIFECYCLE.py',
    'VERIFY_PASS45_GRENADE_THROW_ANIMATION_GATE.py',
    'VERIFY_PASS45_GRENADE_FLASH_GATE.py',
    'VERIFY_PASS45_LANDMARK_IDENTITY.py',
    'VERIFY_PASS45_MUSEUM_REFERENCE_CONTRACT.py',
    'VERIFY_PASS45_MUSEUM_LEGACY_BLOCKOUT_RETIREMENT.py',
    'VERIFY_PASS45_LOCATION_REFERENCE_BINDINGS.py',
    'VERIFY_PASS45_REFERENCE_DRIVEN_RESIDENTIAL_RETIREMENT.py',
    'VERIFY_PASS45_HMMWV_M2_HIERARCHY.py',
    'VERIFY_PASS45_HMMWV_SPEED_HANDLING.py',
    'VERIFY_PASS45_BTR4_AUTHORED_MATERIAL.py',
    'VERIFY_PASS45_BTR4_MATERIAL_STATE.py',
    'VERIFY_PASS45_BTR4_AXIS_REMOTE_OPTIC.py',
    'VERIFY_PASS45_PARK_PRIMARY_SEMANTIC_OWNERS.py',
    'VERIFY_PASS45_AUTHORED_PARK_HARDSCAPE.py',
    'VERIFY_PASS45_VISUAL_FIDELITY_GATE_K.py',
    'VERIFY_PASS45_GATE_K_GLOBAL_BASICSHAPE_SCOPE.py',
    'VERIFY_PASS45_FAST_PREVIEW_PROGRESS.py',
    'VERIFY_PASS45_TREE_STARTUP_DEFERRED.py',
    'VERIFY_PASS45_PRETICK_SECTOR_STARTUP_GUARD.py',
    'VERIFY_PASS45_STALE_RUNTIME_RETIREMENT.py',
]:
    run_verifier(ROOT / verifier)

print('ALL SOURCE + PASS45 FAST PREVIEW VISIBLE STARTUP PROGRESS + PASS45 PRETICK SECTOR/STARTUP GUARD + PASS45 BLOCK0 UE58 RUNTIME HANDOFF + PASS45 CONTENT RUNTIME WIRING + PASS45 BLOCK0 GROUND/SPATIAL GRASS + PASS45 BLOCK0 REGIONAL GROUND DETAIL + PASS45 MUSEUM/SILPO/CULTURE REFERENCE CONTRACTS + PASS45 MUSEUM LEGACY BLOCKOUT RETIREMENT + PASS45 ITEM31 GATE K VISUAL TRUTH + PASS45 PARK PRIMARY SEMANTIC OWNERS + PASS45 AUTHORED PARK HARDSCAPE + PASS45 GLOBAL GAMEPLAY BASICSHAPE SCOPE + PASS45 CHARACTER/COMBAT PROXY RETIREMENT + PASS45 GRENADE TYPE PRESENTATION LIFECYCLE + PASS45 GRENADE THROW ANIMATION GATE + PASS45 FLASH GRENADE GATE + PASS45 FOLIAGE/DEBUG VISUAL CLEANUP + PASS45 BTR4 AXIS/REMOTE OPTIC + BTR4 MATERIAL STATE/AUTHORED MATERIAL + HMMWV SPEED/HANDLING + PASS45 HMMWV M2 HIERARCHY + PASS45 LANDMARK IDENTITY + PASS45 GRENADE/SMOKE PRIMITIVE RETIREMENT + PASS45 PRIMITIVE WEAPON RETIREMENT + PASS45 WEAPON AUDIO FALLBACK + PASS45 WEAPON ADS ALIGNMENT + PASS45 WEAPON ACTION MATRIX/MANUAL CYCLE + PASS45 WEAPON MUZZLE/DROP PHYSICS + PASS45 FALLBACK MATERIAL TEXTURE DEPENDENCY + R14 LAUNCHER OWNERSHIP + PASS45 GATE E REFERENCE-DRIVEN RESIDENTIAL + PASS45 STALE-RUNTIME RETIREMENT + PASS45 WEAPON MATERIAL DEPENDENCY + PASS45 LOCAL BUILD/IMPORT REGRESSION + PASS45 RUNTIME RECOVERY + PASS44 RUNTIME MAP/SPAWN/FPS/ASSETS + PASS43 SLATE STARTUP + PASS42 PRODUCTION VEHICLE/RACK + PASS41 INPUT + PASS40 UI FRAME + PASS39 VISUAL/TICK + PASS38 RUNAWAY/HEAT + PASS37 MUSEUM/PALETTE RETIREMENT + PASS36 WEAPON/PERF + LEGACY STRUCTURAL VERIFIERS: PASS')
