from pathlib import Path
import os
import subprocess
import sys

ROOT = Path(__file__).resolve().parent
ENV = os.environ.copy()
ENV['PYTHONUTF8'] = '1'
ENV['PYTHONIOENCODING'] = 'utf-8'


def run_verifier(path: Path) -> None:
    print(f'===== {path.name} =====')
    result = subprocess.run([sys.executable, str(path)], cwd=ROOT, env=ENV)
    if result.returncode:
        raise SystemExit(result.returncode)


ordered = [
    'S04', 'S05', 'S06', 'S07', 'S08', 'S09', 'S10', 'S11', 'S12', 'S13',
    'S14A', 'S14B', 'S15A', 'S15B', 'S16A', 'S16B', 'S16C', 'S17A', 'S17B',
    'S18A', 'S18B', 'S18C'
]
for tag in ordered:
    file_path = ROOT / f'VERIFY_{tag}.py'
    if file_path.exists():
        run_verifier(file_path)

for verifier in [
    'VERIFY_S18C_HARDENING_R1.py',
    'VERIFY_S19C_SOURCE.py',
    'VERIFY_R6_LAUNCH_KIT.py',
    'VERIFY_R7_LOGIC_PHYSICS.py',
    'VERIFY_R8_UE58_TARGETS.py',
    'VERIFY_R9_UHT_TRAUMA.py',
    'VERIFY_R10_CXX_BATCH_FIX.py',
    'VERIFY_R11_VISUAL_FOUNDATION.py',
    'VERIFY_GAMEPLAY_INPUT_PASS_31.py',
    'VERIFY_MUSEUM_LAYER_BUDGET_PASS_32.py',
    'VERIFY_RUNTIME_ACCEPTANCE_PASS_33.py',
    'VERIFY_RUNTIME_LOCATION_MAP_PASS_35.py',
    'VERIFY_WEAPON_MATERIAL_LOWCPU_PERF_PASS_36.py',
    'VERIFY_VISIBLE_MUSEUM_WEAPON_PALETTE_PASS_37.py',
    'VERIFY_RUNTIME_RUNAWAY_HEAT_PASS_38.py',
    'VERIFY_VISUAL_QUALITY_TICK_BUDGET_PASS_39.py',
    'VERIFY_POSTSTART_FRAME_BUDGET_PASS_40.py',
    'VERIFY_INPUT_RECOVERY_POLL_BUDGET_PASS_41.py',
    'VERIFY_PRODUCTION_VEHICLE_GROUND_RACK_PASS_42.py',
    'VERIFY_SLATE_RENDER_TARGET_STARTUP_PASS_43.py',
    'VERIFY_RUNTIME_MAP_SPAWN_FPS_ASSETS_PASS_44.py',
    'VERIFY_RUNTIME_RECOVERY_PASS_45.py',
    'VERIFY_PASS45_LOCAL_BUILD_IMPORT_REGRESSION.py',
    'VERIFY_PASS45_WEAPON_MATERIAL_DEPENDENCY_AUDIT.py',
    'VERIFY_PASS45_STALE_RUNTIME_RETIREMENT.py',
]:
    run_verifier(ROOT / verifier)

print('ALL SOURCE + PASS45 STALE-RUNTIME RETIREMENT + PASS45 WEAPON MATERIAL DEPENDENCY + PASS45 LOCAL BUILD/IMPORT REGRESSION + PASS45 RUNTIME RECOVERY + PASS44 RUNTIME MAP/SPAWN/FPS/ASSETS + PASS43 SLATE STARTUP + PASS42 PRODUCTION VEHICLE/RACK + PASS41 INPUT + PASS40 UI FRAME + PASS39 VISUAL/TICK + PASS38 RUNAWAY/HEAT + PASS37 MUSEUM/PALETTE RETIREMENT + PASS36 WEAPON/PERF + LEGACY STRUCTURAL VERIFIERS: PASS')
