#include "OCVehicleAudioComponent.h"
#include "Sound/SoundBase.h"
#include "GameFramework/PlayerController.h"
#include "OCAudioUserSettings.h"
#include "OCCharacter.h"
#include "OCVehicleAudioProfile.h"
#include "OCVehicleBase.h"
#include "Components/AudioComponent.h"
#include "Engine/World.h"
#include "Kismet/GameplayStatics.h"
UOCVehicleAudioComponent::UOCVehicleAudioComponent(){PrimaryComponentTick.bCanEverTick=true;SetIsReplicatedByDefault(true);}
void UOCVehicleAudioComponent::BeginPlay(){Super::BeginPlay();EnsureLoops();}
void UOCVehicleAudioComponent::EnsureLoops(){if(!AudioProfile||!GetOwner()||!GetWorld()||GetWorld()->GetNetMode()==NM_DedicatedServer)return;if(!ExteriorEngine&&AudioProfile->EngineExteriorLoop)ExteriorEngine=UGameplayStatics::SpawnSoundAttached(AudioProfile->EngineExteriorLoop,GetOwner()->GetRootComponent());if(!InteriorEngine&&AudioProfile->EngineInteriorLoop)InteriorEngine=UGameplayStatics::SpawnSoundAttached(AudioProfile->EngineInteriorLoop,GetOwner()->GetRootComponent());if(!TireLoop&&AudioProfile->TireRollLoop)TireLoop=UGameplayStatics::SpawnSoundAttached(AudioProfile->TireRollLoop,GetOwner()->GetRootComponent());if(!SkidLoop&&AudioProfile->SkidLoop)SkidLoop=UGameplayStatics::SpawnSoundAttached(AudioProfile->SkidLoop,GetOwner()->GetRootComponent());}
void UOCVehicleAudioComponent::TickComponent(float D,ELevelTick T,FActorComponentTickFunction* F){Super::TickComponent(D,T,F);AOCVehicleBase* V=Cast<AOCVehicleBase>(GetOwner());if(!V||!AudioProfile||!GetWorld()||GetWorld()->GetNetMode()==NM_DedicatedServer)return;EnsureLoops();const float Bus=UOCAudioUserSettings::Get()->GetBusVolume(EOCAudioBus::Vehicles);const float Speed=V->GetSpeedKmh();const float N=FMath::Clamp(Speed/FMath::Max(1.0f,V->GetMaxForwardSpeedKmh()),0.0f,1.0f);const float Pitch=FMath::Lerp(AudioProfile->IdlePitch,AudioProfile->MaxPitch,FMath::Clamp(N+FMath::Abs(V->GetThrottleInput())*0.25f,0.0f,1.0f));bool bInside=false;if(APlayerController* PC=UGameplayStatics::GetPlayerController(this,0)){if(AOCCharacter* C=Cast<AOCCharacter>(PC->GetPawn()))bInside=C->GetCurrentVehicle()==V;else bInside=PC->GetPawn()==V;}if(ExteriorEngine){ExteriorEngine->SetPitchMultiplier(Pitch);ExteriorEngine->SetVolumeMultiplier(Bus*(bInside?0.18f:0.75f));}if(InteriorEngine){InteriorEngine->SetPitchMultiplier(Pitch);InteriorEngine->SetVolumeMultiplier(Bus*(bInside?0.85f:0.0f));}if(TireLoop)TireLoop->SetVolumeMultiplier(Bus*FMath::Clamp(Speed/70.0f,0.0f,0.65f));if(SkidLoop)SkidLoop->SetVolumeMultiplier(Bus*((V->IsHandbrakeApplied()&&Speed>20.0f)?FMath::Clamp(Speed/80.0f,0.0f,0.8f):0.0f));const bool bDriver=V->HasDriver();if(bDriver!=bHadDriver){PlayOneShot(bDriver?AudioProfile->EngineStart:AudioProfile->EngineStop,V->GetActorLocation(),0.85f);bHadDriver=bDriver;}}
void UOCVehicleAudioComponent::PlayOneShot(const TArray<TObjectPtr<USoundBase>>& Set,const FVector& L,float Volume){if(Set.IsEmpty())return;const float B=UOCAudioUserSettings::Get()->GetBusVolume(EOCAudioBus::Vehicles);if(B<=0.0f)return;USoundBase* S=Set[FMath::Abs(++EventSeed)%Set.Num()];if(S)UGameplayStatics::PlaySoundAtLocation(this,S,L,B*Volume,FMath::FRandRange(0.96f,1.04f));}
void UOCVehicleAudioComponent::PlayCollisionServer(float ImpactStrength,const FVector& Location){if(!GetOwner()||!GetOwner()->HasAuthority())return;MulticastCollisionAudio(ImpactStrength>520000.0f,Location,FMath::Rand());}
void UOCVehicleAudioComponent::MulticastCollisionAudio_Implementation(bool bHeavy,FVector_NetQuantize L,int32){if(!AudioProfile)return;PlayOneShot(bHeavy?AudioProfile->CollisionHeavy:AudioProfile->CollisionLight,L,bHeavy?1.0f:0.65f);}
