#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path
import json, re, sys, py_compile

PROJECT = Path(__file__).resolve().parents[2]
SOURCE = PROJECT / 'Source' / 'OsterConflict'
errors=[]; warnings=[]

def fail(msg): errors.append(msg)
def warn(msg): warnings.append(msg)

# Project / target / module checks.
uproject=PROJECT/'OsterConflict.uproject'
if not uproject.exists(): fail('OsterConflict.uproject missing')
else:
    try: data=json.loads(uproject.read_text(encoding='utf-8'))
    except Exception as e: fail(f'uproject JSON invalid: {e}'); data={}
    mods={m.get('Name') for m in data.get('Modules',[])}
    if 'OsterConflict' not in mods: fail('Runtime module OsterConflict missing in uproject')
    if not any(p.get('Name')=='EnhancedInput' and p.get('Enabled') for p in data.get('Plugins',[])): fail('EnhancedInput plugin not enabled')
    if not any(p.get('Name')=='PythonScriptPlugin' and p.get('Enabled') for p in data.get('Plugins',[])): fail('PythonScriptPlugin not enabled for release-map generation')

for target in ['OsterConflict.Target.cs','OsterConflictEditor.Target.cs','OsterConflictClient.Target.cs','OsterConflictServer.Target.cs']:
    p=PROJECT/'Source'/target
    if not p.exists(): fail(f'missing target: {target}')

build=PROJECT/'Source/OsterConflict/OsterConflict.Build.cs'
if not build.exists(): fail('OsterConflict.Build.cs missing')
else:
    bt=build.read_text(errors='ignore')
    for dep in ['Core','CoreUObject','Engine','EnhancedInput','AIModule','NavigationSystem','UMG','Slate','SlateCore']:
        if f'"{dep}"' not in bt: fail(f'Build.cs missing dependency {dep}')

# UHT generated header ordering.
headers=list(SOURCE.rglob('*.h')); cpps=list(SOURCE.rglob('*.cpp'))
for h in headers:
    t=h.read_text(errors='ignore')
    if 'GENERATED_BODY()' not in t: continue
    incs=re.findall(r'^\s*#include\s+["<]([^">]+)[">]',t,re.M)
    expected=h.stem+'.generated.h'
    gens=[i for i in incs if i.endswith('.generated.h')]
    if gens != [expected]: fail(f'{h.relative_to(PROJECT)} expected exactly {expected}, got {gens}')
    elif not incs or incs[-1] != expected: fail(f'{h.relative_to(PROJECT)} generated.h is not the final include')

# UFUNCTION RPC implementations.
allcpp='\n'.join(p.read_text(errors='ignore') for p in cpps)
rpc_count=0
for h in headers:
    t=h.read_text(errors='ignore')
    cm=re.search(r'class\s+OSTERCONFLICT_API\s+([AU]OC\w+)\s*:',t)
    if not cm: continue
    cls=cm.group(1)
    for m in re.finditer(r'UFUNCTION\(([^)]*)\)\s*([^;{]+);',t,re.S):
        spec=m.group(1)
        if not re.search(r'\b(Server|Client|NetMulticast)\b',spec): continue
        decl=' '.join(m.group(2).split())
        names=re.findall(r'([A-Za-z_]\w*)\s*\(',decl)
        if not names: fail(f'{h.name}: cannot parse RPC declaration: {decl}'); continue
        name=names[-1]; rpc_count+=1
        if re.search(rf'\b{re.escape(cls)}::{re.escape(name)}_Implementation\s*\(',allcpp) is None:
            fail(f'{h.relative_to(PROJECT)} RPC {name} missing {name}_Implementation')

# Delimiter/basic source sanity and suspicious merge markers.
for p in headers+cpps:
    t=p.read_text(errors='ignore')
    for a,b in [('(',')'),('{','}'),('[',']')]:
        if t.count(a)!=t.count(b): fail(f'{p.relative_to(PROJECT)} delimiter mismatch {a}{b}')
    if re.search(r'^(<<<<<<<|=======|>>>>>>>)',t,re.M): fail(f'{p.relative_to(PROJECT)} contains merge conflict markers')
    if '#error' in t: warn(f'{p.relative_to(PROJECT)} contains #error directive')

# Python scripts must at least parse outside Unreal.
for p in (PROJECT/'Scripts').rglob('*.py'):
    try: py_compile.compile(str(p), doraise=True)
    except Exception as e: fail(f'Python syntax: {p.relative_to(PROJECT)}: {e}')

# S18B build pipeline invariants.
required_scripts=[
 'Scripts/S18B/BuildS18B.ps1','Scripts/S18B/CREATE_RELEASE_MAP.py','Scripts/S18B/POST_BUILD_AUDIT.py',
 'Scripts/S18B/SMOKE_LOCAL.ps1','Scripts/S18B/COLLECT_RC_LOGS.ps1'
]
for r in required_scripts:
    if not (PROJECT/r).exists(): fail(f'missing build script {r}')
config=(PROJECT/'Config/DefaultGame.ini').read_text(errors='ignore')
if '/Game/Maps/OsterConflict_Runtime' not in config: fail('DefaultGame.ini MapsToCook missing OsterConflict_Runtime')

# Source archive hygiene.
for bad in ['Binaries','Intermediate','Saved','DerivedDataCache']:
    if (PROJECT/bad).exists(): fail(f'forbidden generated directory in source milestone: {bad}')

# Report high-risk source-only limitations, not blockers.
if not (PROJECT/'Content/Maps/OsterConflict_Runtime.umap').exists():
    warn('Release .umap is intentionally absent in source archive and must be generated by CREATE_RELEASE_MAP.py before cook.')

print('S18C PREBUILD STATIC AUDIT')
print(f'project: {PROJECT}')
print(f'C++ headers/sources: {len(headers)+len(cpps)}')
print(f'RPC declarations checked: {rpc_count}')
for w in warnings: print('WARNING:',w)
if errors:
    for e in errors: print('ERROR:',e)
    print(f'PREFLIGHT_S18C: FAIL ({len(errors)} errors)')
    sys.exit(1)
print('PREFLIGHT_S18C: PASS')
